### ISSUE TITLE
ERR_INVALID_URL for node 19.0.0 and 18.12.0

### ISSUE THREAD

**Issue by anno73** [baraklevy20/Supercell-Extractor#11]
I tried to run this for CoC v15.0.3 apk but get following error for node v19.0.0 and 18.12.0:

to_extract_sc contains *.sc with no *_tex.sc files as found in the apk/asstes/sc directory.
runnig on debian within wsl2.

```
Supercell-Viewer$ node --version
v18.12.0
Supercell-Viewer$
Supercell-Viewer$ node extractor.js --folder ../to_extract_sc/
(node:2396) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/deps/undici/undici:11118
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /mnt/d/CloudStorage/Dropbox/Work/Python/ClashOfClans/apk/Supercell-Viewer/src/lzham/lzham.wasm
    at Object.fetch (node:internal/deps/undici/undici:11118:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:393:5)
      at URL.onParseError (node:internal/url:565:9)
      at new URL (node:internal/url:645:5)
      at new Request (node:internal/deps/undici/undici:9472:25)
      at Agent.fetch2 (node:internal/deps/undici/undici:10291:25)
      at Object.fetch (node:internal/deps/undici/undici:11116:28)
      at fetch (node:internal/process/pre_execution:216:25)
      at instantiateAsync (/mnt/d/CloudStorage/Dropbox/Work/Python/ClashOfClans/apk/Supercell-Viewer/src/lzham/lzham.js:1:12296)
      at createWasm (/mnt/d/CloudStorage/Dropbox/Work/Python/ClashOfClans/apk/Supercell-Viewer/src/lzham/lzham.js:1:12906)
      at Object.<anonymous> (/mnt/d/CloudStorage/Dropbox/Work/Python/ClashOfClans/apk/Supercell-Viewer/src/lzham/lzham.js:1:15241) {
    input: '/mnt/d/CloudStorage/Dropbox/Work/Python/ClashOfClans/apk/Supercell-Viewer/src/lzham/lzham.wasm',
    code: 'ERR_INVALID_URL'
  }
}
```

**Comment by jadeops** [comment]
Tried recently with the brawlstars apk. It works with nodejs 16.
```
$ node --version
v16.19.0
```

There were several "unknown tag" messages. Here are the uniq ones
```
Unknown tag:  37
Unknown tag:  38
Unknown tag:  39
Unknown tag:  40
Unknown tag:  42
```
