### ISSUE TITLE
TypeError: fetch failed

### ISSUE THREAD

**Issue by gumyberlol** [baraklevy20/Supercell-Extractor#13]
node:internal/deps/undici/undici:11754
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at node:internal/deps/undici/undici:11754:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: unknown scheme
      at makeNetworkError (node:internal/deps/undici/undici:5019:35)
      at schemeFetch (node:internal/deps/undici/undici:9882:34)
      at node:internal/deps/undici/undici:9752:26
      at mainFetch (node:internal/deps/undici/undici:9771:11)
      at fetching (node:internal/deps/undici/undici:9719:7)
      at fetch (node:internal/deps/undici/undici:9583:20)
      at Object.fetch (node:internal/deps/undici/undici:11753:10)
      at fetch (node:internal/process/pre_execution:315:27)
      at instantiateAsync (C:\Users\ADMIN\Supercell-Viewer\src\lzham\lzham.js:1:12296)
      at createWasm (C:\Users\ADMIN\Supercell-Viewer\src\lzham\lzham.js:1:12906)
}

Node.js v21.2.0

**Comment by Creniks** [comment]
Same error
